### ISSUE TITLE
UA YouTube

### ISSUE THREAD

**Issue by Zihraimer** [asrdri/yt-metabot-user-js#1]
Ґо підтримку UA YouTube ! У нас кремлеботів достобіса...﻿ P.S. Можу допомогти з перекладом, але головне сумісність із UA YT.

**Comment by asrdri** [comment]
Лучше писать на русском или на английском, иначе буду пользоваться переводчиком. Отвечать буду на русском.
Как я понял суть вопроса, вы просите поддержки украинского языка, потому что в украинском сегменте также имеются боты. Поясню несколько важных моментов:
1. Не заблуждайтесь по поводу задач и принципов работы скрипта. Он не "выявляет" подозрительные комментарии и авторов, а помогает узнавать дату регистрации каждой учетной записи. Пометка красным осуществляется для внесенных в сторонний список - этот список ведет автор канала **Наблюдатель Youtube**.
2. Следует определиться с важностью выявления дат регистраций в случае с украинскими ботами. Я не интересовался ситуацией с ними, но могу предположить что разброс дат там будет иметь другой характер. Полезно ли будет узнавать дату регистрации у подозрительных учетных записей?
3. Вы уже можете пользоваться скриптом как есть, просто измените язык интерфейса YouTube на English или Русский. Заработает функция запроса дат регистраций одним кликом (поддержка Украинского может быть добавлена в будущих версиях, также можно форкать или делать пулл реквесты). Если нужен функционал аналогичный стороннему списку и выделения комментариев согласно ему, то предлагаю заняться составлением такого списка аккаунтов.
4. Многое в скрипте настроено под конкретный список ботов. В т.ч. дата-константа и обработка дат в списке. Может оказаться, что вам удобнее будет не ориентироваться на даты регистраций, а просто помечать отобранных авторов. Всё это говорит о том, что для нормальной поддержки (которую вы просите) скорее всего нужно будет создать альтернативную версию скрипта, а не обновлять оригинальную.

В общем, предоставьте больше информации по вашим ботам, и как вы хотите их отбирать и помечать. После этого можно будет подумать о реализации.

**Comment by MaxB22** [comment]
asrdri, добрый день. Может добавите поддержку и белорусского языка?
Спасибо.

**Comment by reyaz006** [comment]
> asrdri, добрый день. Может добавите поддержку и белорусского языка?
Спасибо.

Если получится, выйдет в одном из следующих обновлений. Или уже не нужно?

**Comment by asrdri** [comment]
>asrdri, добрый день. Может добавите поддержку и белорусского языка?
Спасибо.

Если получится, выйдет в одном из следующих обновлений. Или уже не нужно?

**Comment by MaxB22** [comment]
Да, спасибо. Нужно.29.03.2018, 00:34, "asrdri" <notifications@github.com>:
asrdri, добрый день. Может добавите поддержку и белорусского языка?
Спасибо.

Если получится, выйдет в одном из следующих обновлений. Или уже не нужно?

**Comment by Zihraimer** [comment]
Попоробую писать росийским.
Боти которих много в укрЮТюбе єто те же санктпетербурзькие. Поетому их Ви
уже вьічесляете ;) Хиба что они пішут на другие теми так что может спісок
и увеличица но принцип определения тот же. Дякую за оновлення. P.S.
Переходить на другой интерфейс не удобно - дуже.

**Comment by asrdri** [comment]
Беларуская и Български добавлены.

**Comment by MaxB22** [comment]
Спасибо.19.04.2018, 02:45, "asrdri" <notifications@github.com>:Беларуская и Български добавлены.
