### ISSUE TITLE
Metabot Plugin

### ISSUE THREAD

**Issue by kolyan1337tophvh** [asrdri/yt-metabot-user-js#10]
Будет ли когда нибудь скрипт переписан как отдельное расширение для разных браузеров? Чтобы не было прочих костылей типо Violentmonkey и тд.

**Comment by asrdri** [comment]
Его не нужно для этого переписывать. Можно создать расширение для большинства браузеров прямо из имеющегося скрипта. Я этого делать пока не собираюсь, но если кто-то другой сделает - флаг в руки. Если кто-то решится, пусть будет готовым к тому что среди пользователей спрос будет скорее всего как на Chrome, так и на Firefox, а также обновлять при необходимости.

Если говорить о функционале, смена формата на отдельное расширение не предоставит преимуществ, по крайней мере исходя из текущих наших потребностей.

>прочих костылей типо Violentmonkey и тд.

Это не костыли, а качественные движки для скриптов, пользующиеся немалой популярностью и доверием.

**Comment by asrdri** [comment]
Кто-то решил сделать для Chrome: https://github.com/CupIvan/metabot

**Comment by superstrongAI** [comment]
Для Firefox смотрим здесь: https://github.com/superstrongAI/yt-metabot-firefox/releases

**Comment by DarkVoyage** [comment]
Сейчас есть два расширения для Хрома и оба работают намного хуже. Чаще просто не показывают ботов. Одно из них вносит косяки - путает имена авторов комментов по всему Ютубу.

**Comment by asrdri** [comment]
#39
