### ISSUE TITLE
Не работает в опере

### ISSUE THREAD

**Issue by abstain** [asrdri/yt-metabot-user-js#11]
После последнего обновления скрипт отвалился.
Opera 52.0.2871.40
Tampermonkey 4.2.5291

**Comment by asrdri** [comment]
>Tampermonkey 4.2.5291

Версия от 2016 года.

Поставь [это](https://addons.opera.com/en/extensions/details/install-chrome-extensions/) а затем версию [отсюда](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo).

**Comment by tiretrak** [comment]
"Поставь это, затем"
уже не работает

**Comment by asrdri** [comment]
Проверил. Не работает только этап загрузки расширения из Chrome Store.

Как исправить: использовать на данном этапе proxy или VPN, расположенные за пределами России.
