### ISSUE TITLE
Ошибочные подсветки пользователей, как ботов

### ISSUE THREAD

**Issue by artemon55** [asrdri/yt-metabot-user-js#12]
Сегодня открыл случайное [англоязычное видео](https://www.youtube.com/watch?v=x_7tsRrgA2Q).
И самый верхний комментарий пользователя [Diles46](https://www.youtube.com/user/Diles46/about) сразу оказался подсвеченным как бот, что меня и удивило. Еще больше я удивился, когда обнаружил, что у него 56к подписчиков.
Ошибка произошла при первом "чистовом" открытии видео, без всяких репортов и т.п.
Надеюсь это поможет пофиксить этот баг.
P.S. Браузер Opera 52.0.2871.40

**Comment by artemon55** [comment]
Новый или старый это дизайн затрудняюсь ответить. Вот [скриншот моей страницы Youtube](https://drive.google.com/file/d/11gLmfHj1N8vxYNI9ze7nHq78_laVhr0a/view?usp=sharing).
- Да, версия скрипта v180405.
Средней кнопкой не пользуюсь, но возможно открывал через контекстное меню "Открыть в новой вкладке". Затрудняюсь сказать. Действия на предыдущей странице уже, конечно, не помню. 
Напишу, если будет новая информация.

**Comment by asrdri** [comment]
>Вот скриншот моей страницы Youtube.

Да, это новый дизайн.
