### ISSUE TITLE
Автоматическое удаление для владельцев канала

### ISSUE THREAD

**Issue by ghost** [asrdri/yt-metabot-user-js#13]
Предлагаю фичу похожую на автоматическое проставление дизлайков, но для владельцев каналов. В идеале было бы неплохо, если бы скрипт проверял каждый новый комментарий, но думаю подойдет и удаление при скроле страницы

**Comment by asrdri** [comment]
Судя по тому что я знаю - опция удаления канала находится в одном контекстом меню с опцией жалобы на комментарий. Взаимодействия такого уровня  пока не реализовано. И не уверен, что смогу его реализовать.
