### ISSUE TITLE
Отправка жалобы на комментарий

### ISSUE THREAD

**Issue by CupIvan** [asrdri/yt-metabot-user-js#15]
Вроде раньше была такая возможность, но её убрали, почему?
Такое ощущение, что сейчас активизировалось очень много кремлеботов, которых нет в списках.
Нужно сделать обратную связь от пользователей и по статистике жалоб можно отправлять аккаунт в список, либо на ручную проверку.
Так намного эффективнее и оперативнее пополнялась бы база.
Также можно сделать отдельный тип подсветки когда много жалоб, но аккаунта нет в базе.

**Comment by CupIvan** [comment]
как с вами можно связаться? хотелось бы помочь по мере своих сил :-)

**Comment by asrdri** [comment]
>Вроде раньше была такая возможность, но её убрали, почему?

По-моему слишком большой объём жалоб от недостаточно ответственных пользователей.

>Нужно сделать обратную связь от пользователей и по статистике жалоб можно отправлять аккаунт в список, либо на ручную проверку.

Нечто подобное сейчас разрабатывается. По срокам ничего сказать не могу.

>Также можно сделать отдельный тип подсветки когда много жалоб, но аккаунта нет в базе.

Для этого понадобится подгрузка второго списка. Возможно, такая функция будет.

>как с вами можно связаться?

Отправил данные на *@c******.ru.

**Comment by CupIvan** [comment]
кстати по жалобам - можно тоже статистику собирать и по тем кто и на кого жалуется и помечать тех кто злоупотребляет функцией, возможно так и кремлеботов проще найти будет, если они вдруг тоже установят этот скрипт :-)

**Comment by acuna-personal** [comment]
Правильно, неча, а-то сами кремлеботы со временем завалят багрепорт в отместку.

**Comment by CupIvan** [comment]
Так можно же от кремлеботов не принимать багрепорты или если он на всех подряд жалуется - вручную проверить не кремлеботов ли

**Comment by asrdri** [comment]
Текущая ситуация: обратная связь в telegram-группе. Функция отправки отключена из-за того что ей злоупотребляют.
