### ISSUE TITLE
Дополнительный список аккаунтов

### ISSUE THREAD

**Issue by zamanov001** [asrdri/yt-metabot-user-js#16]
Уже не для кого не секрет, что кремлеботы стали использовать новую тактику. Ищется негативный комментарий и на него накручивается огромное количество лайков. В новой версии есть возможность поставить автоматически дизлайк. Так почему бы не создать доп список аккаунтов для сбивания рейтингов?

**Comment by asrdri** [comment]
Кажется, что подобная возможность будет основываться на #8, где решения ещё нет. А вообще:

- Если это будет работать так как я думаю, то дизлайки будут накручиваться не только комментарию обычного человека, который попал под руку ботам, но и всем остальным его комментариям.

- Позволять легко создавать собственный список для дизлайков - чревато тем что кто-то будет создавать списки неугодных лично ему аккаунтов.

- По-моему достоверных сведений о том, что дизлайки сбивают какие-либо рейтинги, пока нет.

**Comment by asrdri** [comment]
В последней версии 180617 добавлена поддержка функционала, который может быть полезен, а именно: Закладки и Дополнительные списки (до 3 штук). См. #23
Вводить поддержку автоматических дизлайков для них не планируется.

**Comment by w00den** [comment]
Новые боты? Жирным курсивом сами пишут. В основной базе не числятся.

```
UC7TLL8BUrHbq92LLdAewCeA=13 Jan, 2018
UC_H5I8CetsG8hNz0nwO6tMw=31 Jan, 2018
UCfcR9cTvQ6t75x-HetLSNSQ=10 Apr, 2016
UCg4T-a1S2yqzgE7rSJW2PEA=2 Jun, 2018
```

<img width="1132" alt="screen shot 2018-06-21 at 8 09 39 pm" src="https://user-images.githubusercontent.com/35340335/41734323-427d93d6-758f-11e8-96eb-f5a32818ed57.PNG">

**Comment by YTObserver** [comment]
w00den, нет, это компашка придурков, которые уже несколько дней пишут хрень под роликами с канала "Навальный Лайв" и "наслаждаются горящими пуканами"
