### ISSUE TITLE
Как проверить работу скрипта в Chrome?

### ISSUE THREAD

**Issue by Xandir-16** [asrdri/yt-metabot-user-js#17]
Добрый день!

Установил скрипт через tampermonkey в Chrome. Кнопочки на роликах ютуб появились но пересмотрев несколько определённых роликов не увидел чтобы хоть один комментарий был подсвечен. Как проверить работу скрипта?

**Comment by Xandir-16** [comment]
Да, работает. Спасибо.

**Comment by Xandir-16** [comment]
А кто пополняет базу ЕРКЮ? Разработчики или пользователи? Как я понимаю база очень мала ибо в новых роликах комментарии кремлеботов не отмечаются.

**Comment by asrdri** [comment]
Пополняет базу Наблюдатель. Сейчас в базе больше 1200 аккаунтов.

Пользователи могут отправлять данные о подозрительных комментариях Наблюдателю. Пока что удобных способов для этого нет. Надеемся что скоро будет.

**Comment by asrdri** [comment]
Актуальный ответ на изначальный вопрос:
Можно открыть любой профиль (канал) пользователя и дождаться сообщения под его именем - найден он в ЕРКЮ или нет.

Можно было бы найти блок комментариев от ботов под определенными видео и ссылаться на них, но со временем аккаунты ботов блокируются, и комментарии исчезают. По ссылке, которую я привёл выше, ранее было более 10 аккаунтов, а сейчас только 1.
