### ISSUE TITLE
Автоматизация 

### ISSUE THREAD

**Issue by koloved** [asrdri/yt-metabot-user-js#18]
Предложение, возможно ли сделать так чтобы скрипт кроме того что дизлайкал ботов
делал следующее:
Отвечал боту допустим "#ЕРКЮ. Это бот. Скачать определитель ботов по ссылке -"

Это бы и сильно продвинуло скрипт в массы и избавило от рутинных действий, которые никто делать в здравом уме не будет

Может бы даже  лайкал комментарий с тегом #ЕРКЮ (но это может обузиться ботами)

**Comment by magicgoose** [comment]
абузиться ботами действительно может, не надо давать им такую возможность.

**Comment by asrdri** [comment]
#48
