### ISSUE TITLE
Баг с отображением некорректной информации на каналах

### ISSUE THREAD

**Issue by Ret0052** [asrdri/yt-metabot-user-js#19]
Данный баг работает только на новом дизайне.
Metabot ошибочно определяет есть ли данный канал в ЕРКЮ. Сообщая о том, что данный канал добавлен в ЕРКЮ, хотя в самих комментариях комментарий конкретно этого канала помечает зелёным.
![78](https://user-images.githubusercontent.com/38890891/39486055-8887694e-4d83-11e8-8443-5794e8993455.png)
Но при заходе на сам канал Metabot пишет что данный канал есть в ЕРКЮ 
![79](https://user-images.githubusercontent.com/38890891/39486143-cba9b768-4d83-11e8-9bdf-eb425cc7233f.png)
Это работает и в обратную сторону. Помечая кремлебота красным в комментариях, при заходе на канал Metabot будет писать что данного канала нет в ЕРКЮ. Пруфы:
![81](https://user-images.githubusercontent.com/38890891/39486252-284e17e8-4d84-11e8-927e-d52e5b82ca98.png)
![80](https://user-images.githubusercontent.com/38890891/39486259-2ac044e2-4d84-11e8-8b88-8c93f2c61144.png)
Баг был обнаружен путём открытия каналов в новой и текущей вкладке. В ходе дальнейших манипуляций было замечено, что если сначала открыть канал кремлебота в текущей вкладке, а затем открыть канал автора в текущей вкладке, то Metabot сообщит, что канал автора есть в ЕРКЮ. Если сначала открыть канал автора в текущей вкладке, а затем открыть канал кремлебота в текущей вкладке, то Metabot сообщит, что канал автора есть в ЕРКЮ. Ссылка на видео, где всё это проверялось https://www.youtube.com/watch?v=deHJJnBRssQ&t=1s

**Comment by asrdri** [comment]
>Помечая кремлебота красным в комментариях

Что это значит? Не подразумевается никакого действия со стороны пользователя?

>Баг был обнаружен путём открытия каналов в новой и текущей вкладке.

В новой вкладке такого не должно быть. Или это точно?

Какой браузер? Желательно, конечно, знать точную последовательность действий.

**Comment by Ret0052** [comment]
> Что это значит? Не подразумевается никакого действия со стороны пользователя?

Некорректно выразился. Я имел ввиду, что данный канал Metabot помечает красным, так как находит его в БД.

> В новой вкладке такого не должно быть. Или это точно?

Сейчас если открыть канал кремлебота, то Metabot будет писать, что данного канала нет в ЕРКЮ.
Браузер google chrome. Последовательность следующая:
1. Открываю по ссылке видео через новую вкладку.
2. Открываю в текущей вкладке канал автора.
3. Наблюдаю, что автора канала в ЕРКЮ нет.
3. Возвращаюсь обратно на видео, нажав на стрелку влево в верхней-левой части экрана у вкладак
4. Захожу на канал кремлебота.
5. Наблюдаю, описанный выше баг

Если сначала зайти на канал кремлебота, а только потом на канал автора, то Metabot будет писать, что канал автора найден в ЕРКЮ.

Если же открывать каналы через новую вкладку, то бага нет.

**Comment by Ret0052** [comment]
Добавлю, что на старом дизайне бага нет.

**Comment by asrdri** [comment]
>Возвращаюсь обратно на видео, нажав на стрелку влево в верхней-левой части экрана

Причина тут. Не предусмотрел повторное открытие другой страницы канала на той же вкладке. Попробую это исправить в следующем обновлении.

А вообще, возвращаться кнопкой Назад на страницу с видео + комментариями в целом мне кажется неэффективным - как минимум сбрасывается положение скролл-бара. И за корректное отображение всех элементов после такого действия я бы не стал ручаться.

**Comment by asrdri** [comment]
Должно быть исправлено в обновлении.
