### ISSUE TITLE
YouTube mobile interface

### ISSUE THREAD

**Issue by DavidSmith478** [asrdri/yt-metabot-user-js#2]
Hello, asrdri.
Thank you for your such a great yt-metabot.user.js
I mentioned that your script:
`@include    https://*youtube.com/*`
But there's a thing: YouTube has its mobile user interface (mobile UI / app interface) via a link - [m.youtube.com](https://m.youtube.com/?app=m)
Sometimes I use User Agent mask on my desktop browser. And your brilliant UserJS, not intended for mobile interface, of course work improperly.

Could you include [m.youtube.com](https://m.youtube.com/?app=m) support along with your next release?
Are there some problems for you?

**Comment by asrdri** [comment]
Basic support for mobile mode added. Currently, the following functions should work on m.youtube.com:
1. Automatic highlighting (red) of comments by known bots.
2. Manual join date requests and highlighting (green/yellow) of corresponding comments.

Known issues:
- Currently, to request join date, you need to touch a comment and release. It should be comfortable enough on mobile touch-screen devices - if you touch and hold for a bit, actions menu will not show up. If you are using desktop browser, you may need to enter mobile mode to enable touch events. I could add click event listener for desktop mouse, but decided against it for now - each click would also bring up the actions menu, and you'd have to press Cancel each time.
- Each time you load more comments (not comment replies), all previously manually-highlighted (green/yellow) comments are going to be reloaded. You may need to touch them again to highlight them. It seems there is no way to fix this for now.

No other functionality for now. Let me know what you think.

**Comment by asrdri** [comment]
Apparently there was a slight design update in mobile interface. I've updated the code to support it.

I've also been able to test the script in actual mobile environment:

- Android
- Firefox browser
- Violentmonkey add-on

I've tried it on m.youtube.com, and the basic support works as expected.

**Comment by asrdri** [comment]
Had to fix it again today. It seems elements class names are being regularly changed on m.youtube.com. I'm not sure how to solve this issue for now, and I may not have enough time for this. I'm leaving it as is for now. Perhaps I'll be able to solve the problem in future or someone else may propose a solution.

Имена классов элементов меняются регулярно, судя по всему, что ломает весь функционал. Пока оставляю как есть, может быть позже появится нормальное решение.

**Comment by asrdri** [comment]
Поддержка мобильной версии удалена начиная с https://github.com/asrdri/yt-metabot-user-js/commit/64c24dfb5b9b0fadf81a4379426cd6a54f8a2aff

Пока не вижу необходимости возобновлять.
