### ISSUE TITLE
Возможность помощи без аккаунта Google

### ISSUE THREAD

**Issue by TAbdiukov** [asrdri/yt-metabot-user-js#20]
Google аккаунт не использую по личным причинам, и при этом не раз попадал на откровенно атакуемые видео, которые никто не замечал (с большим колвом известных ботов). Не можно ли организовать возможность помощи не имея аккаунт Google? Например, через форумы или подобное

Кстати, на ваш опросник не могу ответить по тем же причинам

**Comment by asrdri** [comment]
Что подразумевается под помощью?

**Comment by TAbdiukov** [comment]
@asrdri , да все что угодно, начиная от отправки данных вощможных кремлеботов и заканчивая массовыми анонимными сливами списков интернет-блоггеров, связанных с кремлем (а такое бывает).

У меня, например, года с ~2012 есть список, который нашел на каком-то форуме, примерно 30 больших каналов, которые связаны с какой-то околокремлевской организацией (якобы). Фейк это или нет, я так и не узнал, однако этот список я больше нигде не видел, чтобы всплывал. Я бы мог теоретически отправить его вам на исследование, однако это проблематично как на данный момент, так как подраз умевается, что обратная связь возможна только используя систему аккаунтов Google

**Comment by asrdri** [comment]
Предложили написать в чат https://t.me/YTObserver_chat
Если нужно отправить лично Наблюдателю - @random_anon_338

**Comment by asrdri** [comment]
Актуальная ссылка на чат - в настройках скрипта.
