### ISSUE TITLE
Возможность отвечать самим ботам что они боты

### ISSUE THREAD

**Issue by ointeractive** [asrdri/yt-metabot-user-js#22]
Собственно) Можно и каждому по отдельности. Что-то на подобии кнопки "Сообщить боту что он бот" в комментах, и указывать в комментах их дату регистрации и то, что они находятся в списке. Дополнительно можно ставить тег #Metabot, например, или призыв для других его ставить (плагин).

P. S. И да, огромное спасибо за плагин, просто подарок)

**Comment by asrdri** [comment]
#48
