### ISSUE TITLE
Не отображаются значки

### ISSUE THREAD

**Issue by Stol111** [asrdri/yt-metabot-user-js#24]
![screenshot_2](https://user-images.githubusercontent.com/37815117/41820534-f8d57b14-77db-11e8-8a0c-08fb691257dc.png)
![screenshot_3](https://user-images.githubusercontent.com/37815117/41820541-fd06696e-77db-11e8-9645-4703bdbf188a.png)

**Comment by asrdri** [comment]
Проверил на GoogleChromePortable_67.0.3396.87_online.paf.exe - подобного не увидел. Проблема связана скорее всего не с версией браузера, а с наличием шрифтов в системе. У меня Windows 8.1.

Это unicode emoji, в скрипте для них используется шрифт Segoe UI Symbol. Здесь что-нибудь видно 🔧 📣?

- Если не видно - может быть, в твоей системе отсутствует или сломана поддержка unicode emoji.

- Если видно - может быть, проблема в доступе к шрифту Segoe UI Symbol или его отсутствии. Если не ошибаюсь, он включен во все версии Windows начиная с 7. Можно изменить свойства элементов с тем чтобы использовался следующий доступный шрифт при недоступности этого, но это должно работать по умолчанию без явного указания других шрифтов.

**Comment by Stol111** [comment]
На этом сайте значки отображаются. Но в уведомлении, которое пришло на почту, отображаются квадратики.

**Comment by asrdri** [comment]
Здесь отображаются, потому что тут они автоматически изменились на рисунки. Попробуй здесь http://jsfiddle.net/akLbdrpx/
Если 2 квадрата, то дело не в шрифтах. Нашёл сведения о том что в Windows 7 поддержка эмодзи скорее всего не была включена изначально. Если у тебя Windows 7, может помочь обновление KB2729094, в котором такая поддержка добавлена (либо должен быть корректно установлен IE10/IE11). Ещё можно проверять отображение эмодзи на сайте http://getemoji.com/

Кардинальным решением проблемы будет использование в скрипте картинок или SVG вместо символов, конечно. Но, во-первых, это подразумевает некоторое нагромождение кода. Во-вторых, качество изображений будет плохим на экранах с большим масштабом, и от этого спасёт только SVG, с которым поладить у меня пока не получилось. Если кто-то найдёт хорошие иконки в формате SVG для замены текущих - 🔧 📣 ❓ 📌 ❌ 👎 🔃 - попробую включить их в скрипт вместо эмодзи.
