### ISSUE TITLE
Как СКРЫТЬ комменты из своего списка или закладок?

### ISSUE THREAD

**Issue by NightmarishPuppy** [asrdri/yt-metabot-user-js#25]
Как СКРЫТЬ комменты из своего списка или закладок?

**Comment by asrdri** [comment]
Такой возможности пока нет. Возможно, появится в будущем. Не уверен, что реализация этой возможности будет иметь большой приоритет.

**Comment by NightmarishPuppy** [comment]
как тогда заменить дефолтный список на свой для сокрытия комментаторов с него?

**Comment by asrdri** [comment]
Изменить в коде параметр [ERKYurl](https://github.com/asrdri/yt-metabot-user-js/blob/5f3f58e0b6f5ae2a722714bb6f9a4dbd4e49a2ca/yt-metabot.user.js#L108).

**Comment by NightmarishPuppy** [comment]
Отлично, спасиб, заменил и всё работает. Надеюсь со временем выйдет какая-нибудь версия скрипта metabot по типу "мусора.net" Заточенная именно под скрытие мусора в комментах, где можно сразу с закладок в урну отправлять и главное чтоб даже строки "Комментарий скрыт: пользователь найден в ЕРКЮ" не было, просто полный игнор мусора.
