### ISSUE TITLE
"Белый лист", джентльмены.

### ISSUE THREAD

**Issue by Nigless** [asrdri/yt-metabot-user-js#27]
Есть идея добавить "Белый лист" - список доверенных аккаунтов, на комментарии которых будут ставится лайки, а видео будут продвигаться общими усилиями (опционально).
Например MetaBot будет уведомлять пользователей о выходе видео, пострадавших от атаки кремле-ботов  и, например автоматически ставить лайк (опционально).
Так же подсвечивать комментарии этих аккаунтов на оппозиционных роликах, в целях привлечь внимание пользователей MetaBot для дальнейшей дискуссии в комментариях.

Проводить премодерацию роликов/аккаунтов перед "атакой лайками".
Завербовать доверенных пользователей, задача которых в дальнейшем критиковать и всячески высказываться на (анти)аппозиционных роликах (писать "в топ" конечно не прокатит).

**Comment by asrdri** [comment]
Непонятно, кого можно было бы добавлять в такие списки. Полагаю, схема добавления будет напоминать клуб для избранных.
Система уведомлений и координации "атак лайками" предполагает наличие какой-нибудь инфраструктуры, которая бы находила такие ролики (такой у нас нет).

В конце концов, у нас нет данных о большом количестве пользователей скрипта, которые готовы будут заниматься такой активностью, следовательно нету предпосылок считать, что такие "атаки лайками" окажут серьёзное воздействие.
