### ISSUE TITLE
обновление ссылки в версии для оперы 

### ISSUE THREAD

**Issue by oz322** [asrdri/yt-metabot-user-js#28]
Вы указали во второй ссылке для установки в опере не ту ссылку - указали на версию для андроида, а надо, вроде как, вот эту: https://addons.opera.com/en/extensions/details/tampermonkey-beta/

**Comment by asrdri** [comment]
Разговор про [эту ссылку](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)? Она верная. Не для андроида. Для установки требуется Install Chrome Extensions, ссылка на который дана.

По вашей ссылке старая версия от 2016, её больше не собираются обновлять.
