### ISSUE TITLE
ПРОБЛЕМА! "1ый ответ на комментарий пользователя"

### ISSUE THREAD

**Issue by Brodiachiy** [asrdri/yt-metabot-user-js#3]
проблема в том , что мой 1ый ответ на комментарий пользователя в ветке комментариев под видео, у которого ещё нет других ответов от пользователей - не отправляется и не отображается в ветке комментариев. 

т.е я так понимаю, что мой первый комментарий перехватывается скриптом. из-за этого бага отвечать в ветке комментариев можно только тем пользователям, на комментарии которых уже есть другие ответы пользователей. такие мои ответы сохраняются.

сейчас попробую оставить свой ответ в ветке под видео.  - мой коммент под видео сохранён и отображается.

проблема только с ответами на те комментарии, на которые ещё ни кто не ответил, т.е: "1ый ответный комментарий" в ветке общения под видео не получается( перехватывается программой)

**Comment by asrdri** [comment]
Нужны уточнения.
1. Говорим про случай когда комментариев под видео всего 1 или больше 1?
2. Что конкретно происходит? Ты отвечаешь на комментарий, и он сразу исчезает? Или показывается на какое-то время, а потом исчезает?
3. Если отключить скрипт через расширение или выключить само расширение, а затем проделать то же самое, ситуация будет другой?
4. Какой браузер и версия? Какое расширение?

**Comment by Brodiachiy** [comment]
1) нет. случай, когда под видео много комментариев. есть комментарии с ответами в виде дерева сообщений.и есть одиночные комментарии (в ответ которым ни кто не написал). вот когда я пишу ответ на такой комментарий (первые два ответа на комментарий видны, а не скрыты) когда ты просматриваешь глазами первую страницу с комментариями под видео.  ладно. сейчас накидаю скринов.) 
... немного ещё попробовал разные варианты и увидел одну закономерность. ели оставить 1ый комментарий без ссылки в тексте - то он после перезагрузки страницы остаётся. если оставить со ссылкой - то исчезает. (именно что пропадает КАК ТАК?!) если написать без ссылки, а потом изменить добавив ссылку - то тоже исчезает уже отображавшийся в ветке под комментарием мой комментарий и от него нет даже следа (типа как будто он стал невидимым. нет он исчезает).

2) исчезает комментарий (только с гипер ссылкой в тексте) после перезагрузки страницы.

3) отключал скрипт. отключал расширение вилоетманкей, перезагружал и браузеры (хром и яндекс) перезагружал комп. у меня скрипт не только не отключается - но иногда и двоится. 
 ... ни чего не изменилось. удалять скрипт и расширение вилоетмонкей не стал. слишком нудно тестить ещё большее.

- ситуация не менялась ... да и скрипт работал ??? в выключенном состоянии и после перезагрузок. копаться глубже не стал.

4) браузеры
 - Яндекс Версия17.11.1.988
 - Хром Версия 64.0.3282.140 (Официальная сборка), (64 бит)

расширение Violentmonkey 2.8.28

проще конечно снять наэкранное видео, на я на этом ноуте да и на винде не делал ещё. было бы можно на андроиде - сделал бы сегодня. попробую завтра заморочиться со скринами или видеозахватом.

// надеюсь, что был полезен.
 и СПАСИБО БОЛЬШОЕ за СКРИПТ - он огонь, конечно!

**Comment by asrdri** [comment]
>... немного ещё попробовал разные варианты и увидел одну закономерность. ели оставить 1ый комментарий без ссылки в тексте - то он после перезагрузки страницы остаётся. если оставить со ссылкой - то исчезает. (именно что пропадает КАК ТАК?!) если написать без ссылки, а потом изменить добавив ссылку - то тоже исчезает уже отображавшийся в ветке под комментарием мой комментарий и от него нет даже следа (типа как будто он стал невидимым. нет он исчезает).

Похоже что дело в модерации на YouTube, или настройках авто-модерации на видео, под которыми ты оставляешь комментарии. Другой вариант - твой аккаунт где-то помечен за потенциальный спам.
Поясню тут пару моментов:
1. Следует сразу сказать что комментарий не должен исчезать просто так. По моему (не очень обширному) опыту, твой комментарий после модерации или авто-модерации, не исчезает. Ты сам можешь его видеть. Но если откроешь в другом браузере или с другого аккаунта Google, ты его не увидишь. Не уверен, какая ситуация у тебя. Но в крайнем случае сразу после публикации комментария ты можешь скопировать ссылку на свой комментарий и попробовать открыть её - от своего или другого аккаунта. Предполагаемый результат после авто-модерации: со аккаунта автора комментария автор его видит, а другие пользователя не видят. Если ты со своего же аккаунта его не видишь - такой случай я не наблюдал.
2. Наличие ссылки увеличивает шансы комментария на исчезание - да, это логичное правило для модерации и авто-модерации. У самого бывало такое что послу публикации очередного комментария но с добавлением какой-то ссылки, он исчезает для других пользователей. При этом повторюсь - для меня оне не скрыт - я узнаю о том что он исчез только путём проверки через другие или гостевые аккаунты.

>исчезает комментарий (только с гипер ссылкой в тексте) после перезагрузки страницы.
Полагаю что речь про ручное обновление страницы по F5. Именно так я тестировал. Открыл видео, нашёл комментарий без ответов - ответил, затем обновил страницу по F5.
Вот результаты:
https://www.youtube.com/watch?v=HHEJkAUlYtE&lc=Ugy8WHQDQtAQIHp5yUx4AaABAg.8cNHnQ_syv68c_apKWd54L
https://www.youtube.com/watch?v=HHEJkAUlYtE&lc=Ugx8mV_hTVlQsSbdBTl4AaABAg.8cMwy39iXY88c_ay1KtWYK
Оба тестовых комментария не скрыты, проблем при публикации и после обновления страницы не увидел. Тестировал на Chrome 64.0.3282.140.

>отключал скрипт. отключал расширение вилоетманкей, перезагружал и браузеры (хром и яндекс) перезагружал комп. у меня скрипт не только не отключается - но иногда и двоится.
... ни чего не изменилось. удалять скрипт и расширение вилоетмонкей не стал. слишком нудно тестить ещё большее.
Нужно с этим разобраться. Про "не отключается":
Есть несколько способов отключить или удалить скрипт. В Violentmonkey:
- Жми кнопку расширения, кликай на переключатель рядом со скриптом - выключится.
- Жми кнопку расширения, кликай на переключатель "Скрипты включены" - выключатся все скрипты.
- Правый клик на кнопке расширения - Удалить из Chrome - расширение удалится вместе со скриптами.
Не стесняйся удалять и переустанавливать его и скрипт.

Про "двоится": это скорее всего отдельная проблема, не связанная с твоей (я её пару раз наблюдал, но не смог повторить). Если опишешь точные действия при которых можно это увидеть - опиши как отдельную проблему.

**Comment by Brodiachiy** [comment]
да, ты абсолютно прав!

> Похоже что дело в модерации на YouTube, или настройках авто-модерации на видео, под которыми ты оставляешь комментарии. Другой вариант - твой аккаунт где-то помечен за потенциальный спам.

> Вот результаты:
> https://www.youtube.com/watch?v=HHEJkAUlYtE&lc=Ugy8WHQDQtAQIHp5yUx4AaABAg.8cNHnQ_syv68c_apKWd54L
> https://www.youtube.com/watch?v=HHEJkAUlYtE&lc=Ugx8mV_hTVlQsSbdBTl4AaABAg.8cMwy39iXY88c_ay1KtWYK
> 

вчера и сегодня ещё потестил комментарии - это настройки модерации на каналах, которые продвигают боты. (я прошёл по твоим ссылкам на комментарии и увидел их [а как/где ты берёшь ссылки на свои комментарии???] + повторил сам и комментарий со ссылкой остался).  ... просто эффект того, что сразу после перезагрузки страницы твой комментарий не становится скрытым или прячется под спойлер "ответы", а просто исчезает как будто его только что удалили - немного меня вывело из понимания. ... кстати если первым написать комментарий без ссылки, а второй со ссылкой - то тебе будут видны оба комментария, а тому, кому ты пишешь и с другого аккаунта - только тот, что без ссылки. (так боты борются с распространением информации о них, я думаю)

> Нужно с этим разобраться. Про "не отключается":
> Есть несколько способов отключить или удалить скрипт. В Violentmonkey:

мне просто не хотелось заново всё переустанавливать через ссылки со страницы ютуб. я забыл, что ява скрипт прекрасно копируется в текстовый файл ... вот только потом если добавлять скрипт в Violentmonkey не через гитхаб или другие источники, а через ручное создание .. у меня сего то домашние ссылки в скрипте не работают. ладно фигня. установлю нормально. 

> Про "двоится": это скорее всего отдельная проблема, не связанная с твоей (я её пару раз наблюдал, но не смог повторить). Если опишешь точные действия, при которых можно её увидеть - опиши как отдельную проблему.

я думаю, что это у тех, у кого стоят два браузера, один из которых хром, а второй (типа яндекса) использует расширения и свои и хрома и из оперы.. и если оба браузера включены одновременно - то могут быть накладки  - как это было у меня. и у меня двоился не только скрипт из Violentmonkey но и дополнительные кнопки из расширения YouLike. я отключил YouLike и Violentmonkey в хроме (оставил только в яндексе) и двоение пропало.

----------------
проблема с 1ым комментарием исчерпана - это гадкий гугл и его скрытая политика модерации в ютубе :)))

**Comment by reyaz006** [comment]
>а как/где ты берёшь ссылки на свои комментарии???

Ссылка на отдельный комментарий расположена на метке даты комментария - справа от имени пользователя. Можешь либо скопировать её, либо просто кликнуть сразу после публикации комментария - и страница перезагрузится (насколько это позволяет текущий режим дизайна YouTube) и отобразит твой комментарий первым (не считая оригинальный, если это ответ).

>мне просто не хотелось заново всё переустанавливать через ссылки со страницы ютуб

Не представляю почему это может казаться сложным или нудным. Буквально всё что требуется для установки плагина - перейти по ссылки или найти его по имени и нажать кнопку, то же самое со скриптом. Даже перезагрузка браузера не требуется.

>я думаю, что это у тех, у кого стоят два браузера, один из которых хром, а второй (типа яндекса) использует расширения и свои и хрома и из оперы.. и если оба браузера включены одновременно - то могут быть накладки - как это было у меня. и у меня двоился не только скрипт из Violentmonkey но и дополнительные кнопки из расширения YouLike. я отключил YouLike и Violentmonkey в хроме (оставил только в яндексе) и двоение пропало.

Очень странная догадка. Не думаю что 2 разных браузера могут влиять друг на друга таким образом. В любом случае, если будет информация по воспроизведению этого бага - это было бы полезно.

**Comment by asrdri** [comment]
>а как/где ты берёшь ссылки на свои комментарии???

Ссылка на отдельный комментарий расположена на метке даты комментария - справа от имени пользователя. Можешь либо скопировать её, либо просто кликнуть сразу после публикации комментария - и страница перезагрузится (насколько это позволяет текущий режим дизайна YouTube) и отобразит твой комментарий первым (не считая оригинальный, если это ответ).

>мне просто не хотелось заново всё переустанавливать через ссылки со страницы ютуб

Не представляю почему это может казаться сложным или нудным. Буквально всё что требуется для установки плагина - перейти по ссылки или найти его по имени и нажать кнопку, то же самое со скриптом. Даже перезагрузка браузера не требуется.

>я думаю, что это у тех, у кого стоят два браузера, один из которых хром, а второй (типа яндекса) использует расширения и свои и хрома и из оперы.. и если оба браузера включены одновременно - то могут быть накладки - как это было у меня. и у меня двоился не только скрипт из Violentmonkey но и дополнительные кнопки из расширения YouLike. я отключил YouLike и Violentmonkey в хроме (оставил только в яндексе) и двоение пропало.

Очень странная догадка. Не думаю что 2 разных браузера могут влиять друг на друга таким образом. В любом случае, если будет информация по воспроизведению этого бага - это было бы полезно.
