### ISSUE TITLE
Добавьте возможность поиска комментариев каналов с галочкой на ютубе

### ISSUE THREAD

**Issue by Silvisondarlynn** [asrdri/yt-metabot-user-js#31]
Это кажется ненужным, но прочитать комментарии некоторые хочется. Их сложно найти под кучей ботов. Спасибо заранее.

**Comment by asrdri** [comment]
Не понял, о чём конкретно речь. Но сразу стоит сказать - поиск комментариев по автору на Youtube невозможен, по крайней мере с помощью скрипта. И сервис top30 далеко не всегда с этим справляется в полной мере.

**Comment by asrdri** [comment]
В последнем обновлении добавлена ссылка на top30 на каждую страницу канала. Но сервис всё ещё вряд ли индексирует всех авторов.
