### ISSUE TITLE
Metabot не работает

### ISSUE THREAD

**Issue by oosum** [asrdri/yt-metabot-user-js#34]
Установил violetmonkey, metabot for youtube. Во вкладке "установленные скрипты" metabot присутствует,  но никак себя не проявляет - ботов не отмечает и т.д., всё так, как будто он не установлен.

**Comment by asrdri** [comment]
Вот как можно понять, работает ли скрипт:

1. Открыть любое видео и спуститься к комментариям. Должно выглядеть подобным образом:
![image](https://user-images.githubusercontent.com/36112208/44767970-6983e480-ab68-11e8-9da8-fefc01d6ef3c.png)

2. Открыть любой канал и посмотреть на название. Должно выглядеть подобным образом:
![image](https://user-images.githubusercontent.com/36112208/44768005-8c15fd80-ab68-11e8-8a9d-09a1e401aa8b.png)

Если такие элементы видны, то скрипт работает, и ты просто ещё не встретил ботов. Можно посмотреть комментарии под [этим видео](https://www.youtube.com/watch?v=2aDN8OtEUhg) - там их очень много.

Если элементы не видны, то скрипт не работает.

Почему скрипт может не работать:
- Работает фильтратор трафика, например Adguard или антивирус.
- Имеются сторонние скрипты или расширения браузера, которые препятствуют корректному запуску скрипта. Можно открыть консоль браузера и проверить на наличие ошибок.

**Comment by oosum** [comment]
Раньше скрипт работал, обозначал ботов и обычных пользователей как и полагается, но однажды по каким то причинам перестал работать. На ютубе в violentmonkey появляется строчка "совпадающие скрипты" и под ней "metabot for youtube", его можно отключить и включить, но это ни на что не влияет.

**Comment by asrdri** [comment]
Перечитай мой ответ. Проверь, есть ли в указанных местах показанные элементы. Проверь, включены ли фильтраторы трафика, если они имеются в системе. Проверь содержимое консоли браузера.

В крайнем случае установи Chrome Portable, установи скрипт в него и посмотри, будет ли работать.

**Comment by oldCynic** [comment]
Не уверен, что необходимо создавать новую тему, потому продолжаю здесь.

Обнаружилось, что при *вроде бы* активном скрипте (в наличии иконок "добавить на дизлайкметр", "открыть статистику ..." и "настройки", "последняя информация ...") - отсутствует возможность "взаимодействия" с пользовательскими логинами. 
(Т.е. отсутствуют возможности проверить, пометить, ... [Пример отображения: dropmefiles.com/z8iQ3 - только ник. :()

Win 7 (64 bit), Firefox Quantum 67.0.1 (32 bit), Tampermonkey v. 4.9.5941
(Не отследил, но вероятнее всего проблема возникла после перехода на 67.#.# .)

В Opera 57.0.3098.116 - всё работает. (Т.е. вопрос о локальных настройках фаервола [которые не изменялись] как бы снимается.)

PS Требуется ли какая-либо дополнительная информация?

**Comment by oldCynic** [comment]
Хм... Проблема внезапно исчезла... (После _неудачной_ попытки обновления FF. Без перезагрузки системы и иных действий.)

**Comment by oldCynic** [comment]
Хм... Проблема внезапно исчезла... (После _неудачной_ попытки обновления FF. Без перезагрузки системы и иных действий.)
PS После обновления до 67.0.2 - также вопросов нет. (Всё работает корректно.)

**Comment by asrdri** [comment]
Скорее всего в Tampermonkey не установлены права для скрипта. Окно запроса этих прав должно появляться при обновлении любой страницы Youtube. Проверил текущую версию - чтобы скрипт начал полностью нормально работать, понадобилось 2 раза разрешить ему действия (2 раза обновить страницу и выбрать Allow). Если запрос не появляется, можно вручную добавить: зайти в установленный скрипт, вкладка Settings, XHR Security, User domain whitelist - добавить 2 штуки:

```
raw.githubusercontent.com
github.com
```

Чтобы проверить, имеется ли проблема в скрипте, можно попробовать другое расширение, временно отключив текущее. С Violentmonkey в данном случае ничего не потребовалось делать - заработало сразу.

**Comment by oldCynic** [comment]
Спасибо. Вероятно мой последний пост (дополнение к предыдущему) был отправлен уже когда был готов ответ.

И, да: два "allow" при обновлении скрипта были прожаты, но не помогали. ("Администратор".)

PS Лично у меня возникало желание использовать локальные "дополнительные списки" (file://), но не получилось. Да, понимаю, что это - тема для отдельного разговора/другой ветки. (Буду благодарен, если будет указано что такая уже существует. Если нет - создам "на досуге".)

**Comment by asrdri** [comment]
> file://

Политика безопасности современных браузеров вряд ли подобное позволит. Но можно попробовать поднять локальный http-сервер, например с помощью hfs.

**Comment by Korb** [comment]
> 1. Открыть любое видео и спуститься к комментариям. Должно выглядеть подобным образом:
> (...)
> Если такие элементы видны, то скрипт работает, и ты просто ещё не встретил ботов. Можно посмотреть комментарии под [этим видео](https://www.youtube.com/watch?v=2aDN8OtEUhg) - там их очень много.

То, что отображается на моём скриншоте ниже — это "подобным образом" или нет:

![Image](https://github.com/user-attachments/assets/c45aef6d-3fa0-4402-9cd1-13eaa83700d0)

3—5 — это "очень много" или не очень?

Почти под всеми видео на русскоязычном канале DW их десятки одних и тех же. Никак не помеченных или скрытых вне зависимости от настроек скрипта.

> Если элементы не видны, то скрипт не работает.

Ну, как бы одни видны, а

> Добавлять в закладки и удалять из закладок можно нажатием на соответствующие кнопки image/image над комментарием

не видны.

> Почему скрипт может не работать:
> * Работает фильтратор трафика, например Adguard или антивирус.

Или Microsoft Defender Antivirus? Само собой. MetaBot for YouTube с ним несовместим?

> * Имеются сторонние скрипты или расширения браузера, которые препятствуют корректному запуску скрипта. Можно открыть консоль браузера и проверить на наличие ошибок.

Их много:

```
Content-Security-Policy: Couldn’t process unknown directive ‘require-trusted-types-for’ watch
Error: chrome.declarativeContent is undefined undefined
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:417:1
Request for font "Roboto" blocked at visibility level 2 (requires 3)
node.js:417:1
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. base.js:12126:34
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed). Status code: (null).
The resource at “<URL>” was blocked because content blocking is enabled. 3
Uncaught (in promise) TypeError: field is undefined
    get moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:441
    init moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1130
    waitforinit moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1106
    window["__f__m6rub7gu.52"]/< moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1099
    Pt https://www.youtube.com/watch?v=2aDN8OtEUhg:10
    window["__f__m6rub7gu.52"]/< moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1
    "__f__m6rub7gu.52" moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1
    Pt https://www.youtube.com/watch?v=2aDN8OtEUhg:10
    r https://www.youtube.com/watch?v=2aDN8OtEUhg:85
    <anonymous> https://www.youtube.com/watch?v=2aDN8OtEUhg:88
    _ https://www.youtube.com/watch?v=2aDN8OtEUhg:22
watch:441:7
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. 2Od_BXY8Vjqn5MycIv0XMSA24h9E-qr9j5xv73dxnSQ.js line 2 > eval line 4900 > eval line 1 > eval line 1 > eval:1:97
Request for font "PT Sans Caption" blocked at visibility level 2 (requires 3)
watch
The resource at “https://i.ytimg.com/generate_204” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch
The resource at “https://rr2---sn-gxuo03g-ig3l.googlevideo.com/generate_204” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch
The resource at “https://rr2---sn-gxuo03g-ig3l.googlevideo.com/generate_204?conn2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed). Status code: (null).
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified RotateCookiesPage
Uncaught (in promise) TypeError: field is undefined
    get moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:441
    init moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1130
    waitforinit moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1106
    window["__f__m6ruzifz.aai"]/< moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1099
    Pt https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1:10
    window["__f__m6ruzifz.aai"]/< moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1
    "__f__m6ruzifz.aai" moz-extension://113fe858-8489-4307-8e72-816e6e2317eb/userscripts/MetaBot-for-YouTube.user.js?id=304cfa77-9171-427e-972f-7b7d91c56d0a:1
    Pt https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1:10
    r https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1:85
    <anonymous> https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1:88
    _ https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1:22
RotateCookiesPage:441:7
```

MetaBot for YouTube 230103
Tampermonkey 5.3.3 (December 20, 2024)
Mozilla Firefox 136.0b1 (64-bit)
Microsoft Windows 10.0.19045.5440
