### ISSUE TITLE
Добавьте возможность добавления кремлеботов!!

### ISSUE THREAD

**Issue by jukajuka** [asrdri/yt-metabot-user-js#35]
считаю что необходимо добавить возможность любому пользователю самостоятельно добавлять новых кремлеботов в базу. Думаю что нельзя давать возможность автоматического добавления любым пользователем, так как этим могут воспользоваться сами кремлеботы. Пусть добавления например проходят модерацию автором МетаБота, это ведь облегчит Вам работу!

**Comment by asrdri** [comment]
Пока только так #23 - локально.
Возможность отправлять данные по ранее не замеченным аккаунтам заморожена, альтернатива рассматривается.
