### ISSUE TITLE
Для ютуба

### ISSUE THREAD

**Issue by Ivan-69** [asrdri/yt-metabot-user-js#41]
Сделать дополнение, которое позволяет выбрать любой канал (несколько) и на выбранном канале, при открытии каждого ролика будет выставляться автоматически лайк. При желании лайк можно убрать

**Comment by asrdri** [comment]
В зависимости от того, как конкретно такое будет работать, это можно трактовать как накрутку лайков или как создание инструментов, способствующих накруткам. До такого мы пока не дошли, и доходить не хотелось бы.
>При желании лайк можно убрать
Если лайк убран, то при повторном заходе надо будет либо учитывать, что на данный ролик уже проставлялся лайк, либо снова ставить лайк. И то, и другое непрактично.

Ну и, скорее всего, запрос просто не по тематике скрипта. Для подобного должны быть отдельные скрипты или расширения.

**Comment by Ivan-69** [comment]
Большинство блоггеров будут рады этому скрипты. Много людей просто забывают ставить лайк

**Comment by asrdri** [comment]
>Большинство блоггеров будут рады этому скрипты. Много людей просто забывают ставить лайк

Т.е. блогеры будут рады советовать своим подписчикам ставить вон то расширение и вот этот скрипт чтобы не забывать ставить лайки? А подписчики будут рады следовать этому совету? Всё это очень сомнительно.

Повторюсь:
>Для подобного должны быть отдельные скрипты или расширения.
