### ISSUE TITLE
Плодит иконки "лупы" у первого комментария

### ISSUE THREAD

**Issue by Griff19** [asrdri/yt-metabot-user-js#42]
У первого комментария под видео на YouTube скрипт начинает плодить иконки "Лупы" бесконечно.
![2018-11-22_23-05-51](https://user-images.githubusercontent.com/11175071/48914000-b861c180-eeac-11e8-9927-c8f2e977f3d8.png)
Браузер: Google Chrome Версия 70.0.3538.110 (Официальная сборка), (64 бит)

**Comment by asrdri** [comment]
Это исправлено во вчерашнем обновлении. Версия скрипта должна быть 181121.
