### ISSUE TITLE
Ответьте же!!! 

### ISSUE THREAD

**Issue by AliceeSweet** [asrdri/yt-metabot-user-js#43]
Собственно) Можно и каждому по отдельности. Что-то на подобии кнопки "Сообщить боту что он бот" в комментах, и указывать в комментах их дату регистрации и то, что они находятся в списке. Дополнительно можно ставить тег #Metabot, например, или призыв для других его ставить (плагин).

P. S. И да, огромное спасибо за плагин, просто подарок)
(Репост от другого человека автор не я)

**Comment by Jollfye** [comment]
Неплохая идея, сам иногда бывает копирую имя, дату бота и пишу в ответ для информирования читающих, кого читают. С нескольких ботов выходит как то так:

Сергей ИзМосквы - пользователь найден в #ЕРКЮ, дата регистрации - 22 декабря 2017 [ап]
Евгений Леваков - пользователь найден в #ЕРКЮ, дата регистрации - 6 апреля 2018 [сп]
Андрей Урусов - пользователь найден в #ЕРКЮ, дата регистрации - 13 апреля 2018 [сп]

Но по каждому боту его выделять, копировать, в ответ вставлять выходит муторно и долго, особенно если их много (изначальный коммент-бот и куча ботов ему же в ответ), посему запрашиваю фичу, кнопку рядом с ботом, чтоб вставляла его информацию с переходом на новую строку в новый или уже открытый ответ, новая строка чтобы можно было нажать на следующего бота (в ответах к изначальному комменту-боту) и в общем мой ответ сам с нескольких нажатий (по одному на бота) выходил как я показал на примере выше. Или как то иначе, просто было бы реально удобно в несколько кликов всех ботов рассчитать и в ответ запостить.

**Comment by asrdri** [comment]
Проблема в том, что любая автоматизация по вставке текста в поля ввода приведёт к таким вещам как теневые баны за частую публикацию похожих сообщений. Можно придумать разные шаблоны и чередовать их использование, но всё равно останется шанс, что кого-то заблокируют.

**Comment by IRainman** [comment]
Категорически согласен с @asrdri , не надо никакой самодеятельности. Расширение показывает полезные метаданные пользователю, больше от него ничего не требуется.
