### ISSUE TITLE
Будет ли MetaBot для facebook?

### ISSUE THREAD

**Issue by Baggio824** [asrdri/yt-metabot-user-js#44]
Привет.
Планируется ли MetaBot для facebook?

**Comment by asrdri** [comment]
Моё отношение: я рассмотрю возможность создания скрипта под любую платформу, если для этой платформы появится обновляемый список ботов, которые были добавлены и будут добавляться туда на основе логичного обоснованного подхода. Самый реалистичный сценарий: появится человек или группа, которые мониторили и планируют продолжать мониторить определенную платформу на предмет ботов, после чего они поделятся тут своими изысканиями.

Проще говоря: такого пока не планируется, потому что пока не нашлись люди, разбирающиеся в специфике facebook-ботов. Когда (если) найдутся - не факт, что им потребуется помощь в создании аналогичного скрипта.

**Comment by Baggio824** [comment]
Уже есть группа людей, которые мониторили и будут мониторить. Уже есть порядка 600 ботов в ФБ.
Я вам написал в ВК.

**Comment by asrdri** [comment]
Если ещё актуально, лучше напишите в telegram. Актуальная ссылка есть в кнопке ➤ у комментариев на Youtube.
