### ISSUE TITLE
Скрипт перестал подсвечивать недавно зарегистрированных при клике на иконку у ника

### ISSUE THREAD

**Issue by eternal-sorrow** [asrdri/yt-metabot-user-js#47]
Комментарий подсвечивается зелёным, возле ника зелёная галочка, при наведении на которую всплывает подсказка - дата регистрации раньше 1 июня 2017:
![2019-06-26-001335](https://user-images.githubusercontent.com/4847726/60106011-f204ee80-9753-11e9-9e18-fb95af9af501.png)
Но если открыть страницу "About" этого пользователя, то видно вот что:
![2019-06-26-001452](https://user-images.githubusercontent.com/4847726/60106093-1a8ce880-9754-11e9-90dd-11acb56f24ae.png)
Аккаунту всего полтора месяца.

**Comment by asrdri** [comment]
Скорее всего было исправлено.
