### ISSUE TITLE
Рандомное комментирование

### ISSUE THREAD

**Issue by Alphawerewolf** [asrdri/yt-metabot-user-js#48]
Возможно задать скриптом метаботу не только ботов определять, но и научить расширение комментарии писать [Вставлять], выбрать сотен пять (либо больше) таких, что любому ролику подойдут и пока человек смотрит их публиковать рандомно на отмеченных для этого каналах.

**Comment by FTOH** [comment]
Зачем?

**Comment by Alphawerewolf** [comment]
Чтобы помогать роликам продвигаться в тренды. Вовлеченность аудитории хорошо влияет на продвижение.

**Comment by FTOH** [comment]
Отношение автора к накруткам: https://github.com/asrdri/yt-metabot-user-js/issues/41#issuecomment-439626799

**Comment by Alphawerewolf** [comment]
Ну, на нет, и суда нет :3
