### ISSUE TITLE
Добавь опцию скрытия всех коментариев ботов

### ISSUE THREAD

**Issue by Stol111** [asrdri/yt-metabot-user-js#5]
спасибки!

**Comment by asrdri** [comment]
Следует решить, как оно будет работать. Варианты:

1. Комментарий полностью стирается без следов. Это также удалит все ответы на этот комментарий.

2. Комментарий стирается, но вместо него вставляется пометка о том что он был удалён. То же самое - ответы также удалятся.

3. Комментарий никуда не удаляется, но текст комментария стирается или заменяется. В этом варианте ответы на комментарий останутся на месте.

**Comment by Stol111** [comment]
Ну только не 3 имхо
1 или 2 норм

**Comment by kolyan1337tophvh** [comment]
2 вариант норм

**Comment by artemon55** [comment]
2 вариант + дизлайк на этот коммент.

**Comment by asrdri** [comment]
Теперь можно скрывать комментарии известных ботов вместо подсвечивания. Ответы при этом остаются на месте (решил что их не нужно скрывать или удалять).

**Comment by Stol111** [comment]
Раз пошла такая пьянка, то хорошо бы сделать опцию автоматического проигрывания всех видео со скоростью 1.25 и старт всех видео автоматом с 1-й минуты
