### ISSUE TITLE
Автоматизация отправки жалоб

### ISSUE THREAD

**Issue by voron434** [asrdri/yt-metabot-user-js#51]
На [вашем лендинге](https://kremlebot.rip/) вы круто и доходчиво объяснили как отправить жалобу на ботов и почему это полезно. Почему бы не автоматизировать это? Скрипт мог бы делать это за пользователей, может, по клику определённой галочки.

Из очевидных неприятных последствий — если кто-то лишний попадёт в вашу базу — его скорее всего тут же забанят. Поэтому такой шаг стоит предпринимать только в случае полной уверенности в базе.

**Comment by asrdri** [comment]
Примерно с самого начала была реализована полуавтоматическая (по кнопке) отправка ссылок на подозрительные комментарии автору списка ЕРКЮ, через внутреннюю систему сообщений. Спустя некоторое время отправку таких сообщений запретили без прохождения reCAPTCHA (еще позже от системы планово избавились, но не суть). Это говорит о том что автоматизированные запросы типа submit являются нежелательными для сервиса. В [старой версии правил пользования](https://www.youtube.com/t/terms?archive=20180525) это чётко прописано - см. пункт 5.1H (в [новой версии](https://www.youtube.com/static?template=terms) примерно то же самое есть в блоке Permissions and Restrictions - 3).

Я решил больше не автоматизировать запросы типа submit. Автоматизация проставления дизлайков под комментариями ботов это исключение, потому что во-первых до сих пор нет уверенности в том что количество дизлайков как-то влияет на положение комментария, во-вторых запросы отправляются со значительными интервалами (должно удовлетворить пункт 5.1H), в-третьих эта опция по умолчанию отключена.

Отправка жалоб на пользователя или канал в какой-то момент также требовала прохождения reCAPTCHA (не знаю, как сейчас, но и это не самое важное, потому что вполне реально автоматизировать появление и заполнение формы). Важно то, что отправка большого количества жалоб неизбежно будет замечена системой, и будет приравнена к манипуляции (дальше последует дальнейшая борьба с автоматизацией и отсеивание жалоб как ненадлежащих). Важно и то, что на руках будет инструмент проведения таких манипуляций. Уверенность в базе здесь не будет играть значения, потому что инструмент можно будет использовать на любой другой базе.

**Comment by IronBug** [comment]
а нельзя как-то нормально сообщать о ботах. раньше работало сообщение о боте, а теперь требует какой-то телеграм. я вот не фанат попсы, проприетарщины и анальных зондов, привязанных к телефону. телеграмом не пользуюсь, как и многие программисты. сделайте сообщение о боте через мыло, или IRC, например. а ещё лучше - какие-нибудь API. можно даже не пихать их в ютуб, а сбоку поставить - кто захочет, будет использовать.

**Comment by asrdri** [comment]
> а нельзя как-то нормально сообщать о ботах? раньше работало сообщение о боте, а теперь требует какой-то телеграм. я вот не фанат попсы, проприетарщины и анальных зондов, привязанных к телефону. телеграмом не пользуюсь, как и многие программисты. сделайте сообщение о боте через мыло, или IRC, например. а ещё лучше - какие-нибудь API. можно даже не пихать их в ютуб, а сбоку поставить - кто захочет, будет использовать.

Готов обсудить это в отдельной ветке.
