### ISSUE TITLE
Не работает в принципе

### ISSUE THREAD

**Issue by xPomaHx** [asrdri/yt-metabot-user-js#52]
в консоль 
```
VM3159:38 Refused to connect to "https://raw.githubusercontent.com/YTObserver/YT-ACC-DB/master/announcement.txt": URL is not permitted: No @connects given, but strict mode enabled
eval @ VM3159:38
eval @ VM3159:20
(anonymous) @ VM3145:3
b @ VM3145:2
message @ VM3159:20
message @ VM3159:20
eval @ VM3159:77
V @ VM3145:10
e @ content.js:6
send @ content.js:8
postMessage @ content.js:8
(anonymous) @ content.js:17
VM3159:38 Refused to connect to "https://raw.githubusercontent.com/FeignedAccomplice/Un-Yt-Kb-Rg/master/Un-Yt-Kb-Rg.CSV": URL is not permitted: No @connects given, but strict mode enabled
eval @ VM3159:38
eval @ VM3159:20
(anonymous) @ VM3145:3
b @ VM3145:2
message @ VM3159:20
message @ VM3159:20
eval @ VM3159:77
V @ VM3145:10
e @ content.js:6
send @ content.js:8
postMessage @ content.js:8
(anonymous) @ content.js:17
VM3159:38 Refused to connect to "https://github.com/asrdri/yt-metabot-user-js/raw/master/list-sample.txt": URL is not permitted: No @connects given, but strict mode enabled
```

всё что сделал просто поставил скрипт зашёл в видос ютуба
хром последний

Tampermonkey®
v4.9 by Jan Biniok

добавление директив @connects тоже не помогает

**Comment by asrdri** [comment]
1. Поставил последний Chrome Portable: https://portableapps.com/apps/internet/google_chrome_portable

2. Поставил Tampermonkey: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

3. Поставил скрипт yt-metabot-user-js.

4. Открыл на новой вкладке YouTube.
Получил всплывающее окно от Tampermonkey с текстом **Пользовательский скрипт хочет получить доступ к стороннему ресурсу.**
Окно с таймером - если не отреагировать, то оно само закроется. Чтобы оно открылось ещё раз, надо заново открыть YouTube.

5. Дал разрешение раз, второй, третий (на каждую ссылку).

6. Всё работает.

**Comment by xPomaHx** [comment]
Да действительно всё заработало, кажется у меня настройки строгие стояли. Не ожидал такого потому, что сам когда писал скрипт без особых проблем обходил корс и без запросов пользователя.
