### ISSUE TITLE
Сократите или уберите текстовую подпись-паразит

### ISSUE THREAD

**Issue by Lantcoder** [asrdri/yt-metabot-user-js#54]
Здравствуйте, уважаемые разработчики плагина Metabot!

На Youtube под каждым видео сразу ниже названия ролика есть строка состояния, где находятся сведения: дата добавления видео, количество лайков, дизлайков, "Сохранить" и "Пожаловаться". Строка очень короткая, обычно туда вставляют значки плагинов, также там появляется ваш значок, открывающий статистику видео на Dislikemeter.

Однако если видео не было добавлено, ваш плагин выводит строку-паразита "ДОБАВИТЬ ВИДЕО НА АНАЛИЗАТОР ДИЗЛАЙКМЕТР". Это приводит к тому, что такая длинная надпись паразит закрывает собой другие значки, закрывает дату создания видео, ну в-общем это очень неудобно, ну вы поняли.

У меня к вам предложение. Если вам так нравятся длинные подписи-паразиты, сделайте её длиннее, например "ДОБАВИТЬ ПРОСМАТРИВАЕМЫЙ ВИДЕОРОЛИК НА САЙТ АНАЛИЗАТОР ДИЗЛАЙКМЕТР HTTPS://DISLIKEMETER.COM ДЛЯ ТОГО ЧТОБЫ ОН ПОЯВИЛСЯ В СПИСКЕ АНАЛИЗИРУЕМЫХ ВИДЕО НА ЭТОМ САЙТЕ" (шютка). Ну вы поняли о чём я. Ваша подпись паразит просто бесит.

**Comment by denizzzka** [comment]
Или просто перенести эту подпись на следующую строку

**Comment by Lantcoder** [comment]
Ну если так смотреть, то эта строка предназначена для пиктограмм. Никакого текста там быть не должно. Можно нарисовать изменённую пиктограмму с плюсиком, при наведении на неё появляется текстовая подпись "Добавить"

**Comment by rever58** [comment]
Пришлось пока ОТКЛ.........Жду исправления

**Comment by Lantcoder** [comment]
Исправлено!
