### ISSUE TITLE
Сократить или убрать подпись-паразит у каналов

### ISSUE THREAD

**Issue by Lantcoder** [asrdri/yt-metabot-user-js#55]
Здравствуйте, уважаемые разработчики плагина Метабот! Как говорят, хороший интерфейс это такой которого как бы не видно, но он присутствует. Как говорится, всего в меру, как сказал джавахарлал неру. Плагин должен быть хорошим и по содержанию, и по форме. Ну или по функционалу и по внешнему виду. Большое спасибо что вы удалили подпись-паразит внизу строки, но надо продолжать!

Обратите внимание на строку, которая появляется при открытии любого ютуб-канала (см. скрин). Ну вот варламова взяли. "ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН В ЕРКЮ!". Ну естественно, что Ютуб задумывался не для ботоводства, и уж 99.99...% всех каналов на Ютубе не принадлежат коварным кремлеботам. Зачем выводить эту подпись-паразита напротив каждого канала? Это всё равно что плакат нельзя материться с перечёркнутым хером "У нас не матерятся". Зачем так заострять внимание? В 99.99% этого не надо. Слушаем музыку на Ютубе - "ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН В ЕРКЮ", смотрим кино - опять этот паразит. Хорошего должно быть в меру! Нашли - вывели. Нет - не выводим. В крайнем случае какой-то значочек малозаметный чтоб не сильно внимания отвлекало
![20210228 - Глюк Метабота](https://user-images.githubusercontent.com/34796432/109398835-cd720880-7971-11eb-9721-1443cb20f589.jpg)

**Comment by denizzzka** [comment]
> Ну естественно, что Ютуб задумывался не для ботоводства, и уж 99.99...% всех каналов на Ютубе не принадлежат коварным кремлеботам. Зачем выводить эту подпись-паразита напротив каждого канала? 

Для индикации того что плагин работает, например

**Comment by asrdri** [comment]
>Большое спасибо что вы удалили подпись-паразит внизу строки, но надо продолжать!

Если это про кнопку Дизлайкметр, то эта подпись появилась на этой неделе, из-за изменений на Youtube. Оно так не задумывалось, и конечно было исправлено.

Надпись "ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН В ЕРКЮ" работает как изначально задумывалось. Если её нет - то непонятно, работает ли скрипт.

>В крайнем случае какой-то значочек малозаметный чтоб не сильно внимания отвлекало

Блок изначально не должен бросаться в глаза. При появлении не смещает основной блок снизу, ярких цветов не содержит.
Можешь предложить что-нибудь конкретное, если считаешь, что можно лучше.

**Comment by Lantcoder** [comment]
> Надпись "ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН В ЕРКЮ" работает как изначально задумывалось. Если её нет - то непонятно, работает ли скрипт.
Там же есть значок "i" и "top30", по которым видно что плагин активен. Небольшие, вполне уместные и не раздражают

**Comment by asrdri** [comment]
В последнем обновлении внешний вид этих элементов обновлён. Так лучше?

**Comment by Lantcoder** [comment]
Тип топ!
