### ISSUE TITLE
Подствечивать ботов в чате трансляций(стримов)

### ISSUE THREAD

**Issue by T1mL3arn** [asrdri/yt-metabot-user-js#6]
Фиче-реквест в заголовке. Сейчас скрипт подсвечивает только комментарии. А было бы неплохо, если бы подсвечивал еще и сообщения в чате трансляций.

**Comment by asrdri** [comment]
Хотелось бы это реализовать, но в чатах трансляций элементы сообщений не содержат id каналов пользователей - основной текст, на основе которого скрипт может находить ботов. id можно получить, отправив отдельный GET-запрос. Это значит что для массового определения нужно посылать 1 запрос на каждое сообщение в чате. Скорее всего такая модель поведения будет нежелательной. Если кто-то может помочь с поиском приемлемых данных для идентификации в чатах без отправки отдельных запросов на сервер - было бы хорошо.

**Comment by kolyan1337tophvh** [comment]
Врятле они будут заниматься этим в активном и быстро летящем чате. Скорее только после того как трансляция будет опубликована, надо ли это?

**Comment by asrdri** [comment]
Нет, боты в чатах определенно были зафиксированы, ещё несколько месяцев назад сам наблюдал. Не могу сказать сколько их было в масштабе общего количества пользователей - скорее всего мало, но были. Сколько их сейчас в чатах, тоже сказать затрудняюсь.

**Comment by asrdri** [comment]
Добавлены следующие возможности:

- В живом чате и в записях чатов - при вызове контекстного меню рядом с пользователем, если он обнаружен в списке известных ботов - ссылка на профиль будет подсвечена красным цветом, к тексту добавится дата его регистрации. Если не обнаружен - появится меню в стандартном виде. На живых примерах не удалось протестировать - не нашёл.
- На страницах каналов всех пользователей - заметка под именем, уведомляющая о том, найден ли пользователь в списке ЕРКЮ или нет. Со ссылкой на страницу с датой регистрации.

Пока получилось только так. Возможно, это хотя бы немного облегчит работу тем, кто захочет мониторить чаты.

**Comment by asrdri** [comment]
Поддержка данной функции удалена начиная с https://github.com/asrdri/yt-metabot-user-js/commit/64c24dfb5b9b0fadf81a4379426cd6a54f8a2aff

Из-за изменений на Youtube теперь такая поддержка проблематична - в элементах страницы больше нету ID пользователей. Можно пытаться идентифицировать через ID фотографий. Пока не замечаю спроса на такой функционал, также не было найдено подтверждений активности ботов в чатах.
