### ISSUE TITLE
Как создать свой список ботов/подозрительных аккаунтов?

### ISSUE THREAD

**Issue by Gorshochekvari** [asrdri/yt-metabot-user-js#8]
Хочу завести свой список или даже пару списков, чтобы не заваливать репортами наблюдателя, а самой собрать статистику по определенным аккаунтам и потом уже отправить ему в удобоваримом виде. Мне нужно, чтобы была возможность добавления id в лист и чтобы эти акки подсвечивались сразу, как это происходит с ботами. Цвет подсветки я сама поменяю, но это, наверное, всё, что я могу сделать сама, потому что не программист от слова совсем. Есть ли возможность объяснить чайнику вроде меня, как создать файл под список и что добавить в код скрипта, чтобы он этот список считывал? Заранее, спасибо)

**Comment by asrdri** [comment]
Если нужно чтобы работало по точно такой же схеме, как сейчас работает список ЕРКЮ, то самый простой способ - скопировать скрипт, переименовать уникальные поля в заголовке, установить как второй скрипт, а затем удалять из кода всё ненужное, оставив только функционал по авто-подсветке. Затем заменить ссылку на основной список своей и изменить цвет подсветки. Неудобство в том что для обновления списка нужно каждый раз загружать файл в своё хранилище (можно также использовать github как хранилище). Ну и в целом даже зачистка кода будет сложновата для чайника - скорее всего останутся задвоенные функции и элементы интерфейса.

Предполагаю, что могут быть варианты проще. Одна из функций, которые обсуждались на этапе создания скрипта - локальные списки. Сейчас занимаюсь реализацией настроек, что позволит добавить такую функцию. Это будет работать примерно так: замечаешь комментарий, который хочешь добавить в свой список - жмёшь кнопку рядом с этим комментарием, его автор добавляется в список и в будущем будет помечаться другим цветом. Список будет накапливаться и будет доступен для копирования или изменения вручную в настройках. Но на это всё может уйти ещё несколько недель.

>чтобы не заваливать репортами наблюдателя

Сомневаюсь, что можно завалить, если эти репорты действительно по делу.

**Comment by Gorshochekvari** [comment]
Спасибо за ответ. Попробую вторым скриптом сделать.
В том-то и беда, что эмоции порой берут верх и начинаешь репортить чуть ли не всех подряд. Промежуточный список вполне мог бы полечить эту проблему, хотя бы в моем случае.

**Comment by asrdri** [comment]
В последней версии 180617 добавлен данный функцонал, а именно: Закладки и Дополнительные списки (до 3 штук). См. #23
