### ISSUE TITLE
Как я попал в список кремлеботов и как это опретоставать?

### ISSUE THREAD

**Issue by ivaiva1190** [asrdri/yt-metabot-user-js#9]
Я, главное, всем в комментариях рассказываю, чтобы ставили MetaBot, и вдруг обнаруживаю, что сам попал в этот список, только потому, что у меня пустой канал?
Посмотрите мои комментарии (пользователь ivaiva1190) - они никогда не были прокремлевской направлености! Прозошло это, вероятно, только из-за сиуации по Вострикову - люди разделились надвое. Но кремлеботы топят явно в его поддержку. Я же везде пишу, что он агент кремля (легко проверить).
Как опротестовать попадание в список? Я обычный человек!

**Comment by asrdri** [comment]
По этому поводу стоит писать Наблюдателю Youtube - сообщением или комментарием на его канал, или комментарием нв группу VK.

Обрати внимание:

>всем в комментариях рассказываю, чтобы ставили MetaBot

Из того что я знаю, в последних видео Наблюдатель Youtube этого делать не рекомендует.

>сам попал в этот список, только потому, что у меня пустой канал?

Пока что нигде не может быть указана причина попадания в список. Почему был сделан такой вывод? Также важно помнить, что подсветка красным может быть ошибочной в непредвиденном случае - такие случаи следует описывать здесь, с описанием действий, которые этой проблеме предшествовали.

>Посмотрите мои комментарии

Попробовал - не нашёл. Найти пользователя по нику сейчас даже через Google скорее не получится, а отдельные комментарии пользователя - тем более. Нужно знать твой channel ID - из ссылки на твой профиль из любого твоего комментария, она выглядит так https://www.youtube.com/channel/ID

**Comment by YTObserver** [comment]
Ваш ID, пожалуйста.

Вы отправляли жалобы (например на спам)?

**Comment by ivaiva1190** [comment]
Воспользовался ссылкой топ30 скрипта:
https://www.t30p.ru/search.aspx?s=UCYGlwfmcixZ53HRReNt1Rrg

**Comment by asrdri** [comment]
Последнее обновление базы было не сегодня, это значит что id UCYGlwfmcixZ53HRReNt1Rrg и не было в базе. Значит, это было ложное срабатывание в новом дизайне YouTube. Пока что замечено, что такое может случаться, если в рамках одного ролика пользователь отправляет жалобы Youtube на комметарии пользователей, меняет сортировку. Возможно, высокая скорость действий также увеличивает вероятность такой проблемы. Возможно, если одновременно с этим публиковать комментарии или ответы, также увеличивается вероятность.

Чтобы даже попытаться исправить это, нужно чтобы кто-то сообщил последовательность действий, которая приводит к проблеме, чтобы можно было её воспроизвести.

**Comment by ivaiva1190** [comment]
Ясно. Спасибо. Извините за беспокойство. Если обнаружу еще раз, постараюсь отследить последовательность.

**Comment by Furnicarium** [comment]
у меня было то же самое, я уже было решил, что попал в список, но после обновлений страницы всё прошло, видимо, это после ответов на комментарии бота и жалобы на него через новое окошко для ответов на комментарии от ютуба, всё из-за нового дизайна
